config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'boards#index'
  resources :boards, shallow:true do
    resources :tasks do
      resources :comments
    end
  end
  
  resource :profile, only: [:show, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
# == Schema Information
#
# Table name: boards
#
#  id          :bigint           not null, primary key
#  description :text
#  title       :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :bigint
#
# Indexes
#
#  index_boards_on_user_id  (user_id)
#
class Board < ApplicationRecord
    belongs_to :user
    has_many :tasks, dependent: :destroy
    validates :title, presence: true
    validates :description, presence: true
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :bigint           not null, primary key
#  content    :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  task_id    :bigint
#  user_id    :bigint
#
# Indexes
#
#  index_comments_on_task_id  (task_id)
#  index_comments_on_user_id  (user_id)
#
class Comment < ApplicationRecord
    has_one_attached :eyecatch

    belongs_to :task
    belongs_to :user
end

app/models/profile.rb
# == Schema Information
#
# Table name: profiles
#
#  id           :bigint           not null, primary key
#  gender       :integer
#  introduction :text
#  nickname     :string
#  subscribed   :boolean          default(FALSE)
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  user_id      :bigint           not null
#
# Indexes
#
#  index_profiles_on_user_id  (user_id)
#
class Profile < ApplicationRecord
    has_one_attached :avatar
    belongs_to :user
    enum gender: { male: 0, female: 1, other: 2 }
end

app/models/task.rb
# == Schema Information
#
# Table name: tasks
#
#  id         :bigint           not null, primary key
#  content    :text
#  limit      :datetime
#  title      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  board_id   :bigint
#  user_id    :bigint
#
# Indexes
#
#  index_tasks_on_board_id  (board_id)
#  index_tasks_on_user_id   (user_id)
#
class Task < ApplicationRecord
    has_one_attached :eyecatch
    has_many :comments, dependent: :destroy

    belongs_to :user
    belongs_to :board

    validates :title, presence: true
    validates :content, presence: true
    validates :limit, presence: true


    def comment_count
        comments.count
    end

    def comment_user
        comments.user
    end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :boards, dependent: :destroy
  has_many :tasks, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_one :profile, dependent: :destroy

  delegate :introduction, :gender, to: :profile, allow_nil: 'true'

  def display_name
    #ぼっち演算子
    profile&.nickname || self.email.split('@').first
  end

  def prepare_profile
    profile || build_profile
  end

  def avatar_image
    if profile&.avatar&.attached?
      profile.avatar
    else
      'icon_image.jpg'
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!

    def after_sign_in_path_for(resource)
        root_path # ログイン後に遷移するpathを設定
      end
    
      def after_sign_out_path_for(resource)
        root_path # ログアウト後に遷移するpathを設定
      end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
    before_action :authenticate_user!, only: [:show,:new]
    def index
        @boards = Board.all
    end

    def show
        @board = Board.find(params[:id])

    end

    def new
        @board = Board.new
    end

    def create
        @board = current_user.boards.build(board_params)
        if @board.save
            redirect_to board_path(@board), notice: '保存できました'
        else
            flash.now[:error] = '保存に失敗しました'
            render :new
        end
    end

    def edit
        @board = current_user.boards.find(params[:id])
    end

    def update
        @board = current_user.boards.find(params[:id])
        if @board.update(board_params)
            redirect_to board_path(@board), notice: '保存できました'
        else
            flash.now[:error] = '保存できませんでした'
            render :edit
        end
    end

    def destroy
        @board = current_user.boards.find(params[:id])
        if @board.destroy!
            redirect_to root_path, notice: '削除できました'
        else
            flash.now[:error] = '削除できませんでした'
        end
    end


    private
    def board_params
        params.require(:board).permit(:title, :description)
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    
    def index
        @comments = Comment.all
    end
    def new
        task = Task.find(params[:task_id])
        @comment = task.comments.build
    end

    def create
        task = Task.find(params[:task_id])
        @comment = task.comments.build(comment_params)
        if @comment.save!
            redirect_to task_path(task), notice: 'コメントを追加しました'
        else
            flash.now[:error] = '保存に失敗しました'
            render :new
        end
    end
    def show
        @comment = Comment.find(params[:id])
    end


    private
    def comment_params
        params.require(:comment).permit(:content, :eyecatch).merge(user_id: current_user.id)
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
    before_action :authenticate_user!
    def show
        @profile = current_user.profile
    end

    def edit
        @profile = current_user.prepare_profile
    end

    def update
        @profile = current_user.prepare_profile
        @profile.assign_attributes(profile_params)
        if @profile.save!
            redirect_to profile_path, notice: '更新できました'
        else
            flash.now[:error] = '更新できませんでした'
            render 'edit'
        end
    end

    private
    def profile_params
        params.require(:profile).permit(
            :nickname,
            :introduction,
            :gender,
            :subscribed,
            :avatar
        )
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    def new
        board = Board.find(params[:board_id])
        @task = board.tasks.build
    end

    def create
        board = Board.find(params[:board_id])
        @task = board.tasks.build(task_params)
        if @task.save
            redirect_to board_path(board), notice: 'タスクを追加しました'
        else
            flash.now[:error] = 'タスクを作成できませんでした'
            render :new
        end
    end

    def show
        @task = Task.find(params[:id])
    end

    def destroy
        @task = Task.find(params[:id])
        if @task.destroy!
            redirect_to board_path(@task.board_id), notice: 'タスクを削除しました'
        else
            flash.now[:error] = '削除に失敗しました'
        end
    end

    def edit
        @task = Task.find(params[:id])
    end 

    def update
        @task = Task.find(params[:id])
        if @task.update(task_params)
            redirect_to task_path(@task), notice: '保存できました'
        else
            flash.now[:error] = '保存できませんでした'
            render :edit
        end
    end

    private
    def task_params
        params.require(:task).permit(:title, :content, :limit, :eyecatch).merge(user_id: current_user.id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/boards/_form.html.haml
.container
    - if current_page?(new_board_path)
        %h2.section-top New Board
    - elsif current_page?(edit_board_path(board.id))
        %h2.section-top Edit Board
    - board.errors.full_messages.each do |message|
        %ul
            %li=message
    = form_with(model: board, local: 'true') do |f|
        %div
            = f.label :title, "Name"
        %div
            = f.text_field :title, class: 'text'
        %div
            = f.label :description
        %div
            = f.text_area :description, class: 'text'
        %div
            = f.submit "Submit", class: 'btn-primary'

app/views/boards/edit.html.haml
= render 'form', board: @board

app/views/boards/index.html.haml
.container
    %h2.section-top All Boards
    - @boards.each do |board|
        = render 'commons/board', board: board
    .card_add_board
        = link_to '+ Add new board', new_board_path

app/views/boards/new.html.haml
= render 'form', board: @board

app/views/boards/show.html.haml
.container
    %h2.section-top= @board.title
    
    - if @board.tasks.present?
        - @board.tasks.each do |task|
            = link_to task_path(task) do
                .card
                    - if task.eyecatch.attached?
                        .card_image
                            = image_tag task.eyecatch
                    .card_top
                        = task.title
                    .card_content
                        内容：
                        = task.content
                    .card_limit
                        期限：
                        = task.limit.strftime('%Y年%m月%d日')
                    .card_comment
                        .card_user
                            = image_tag task.user.avatar_image, class: 'user_image'
                        .card_comment_count
                            = fa_icon 'pencil'
                            = task.comment_count
    .card_add_board
        = link_to '+ Add new Card', new_board_task_path(@board)

app/views/comments/_form.html.haml
.container
    - if current_page?(new_task_comment_path)
        %h2.section-top New Comment
    - comment.errors.full_messages.each do |message|
        %ul
            %li=message
    = form_with(model: comment, url: task_comments_path(comment.task), local: true) do |f|
        %div
            = f.label :comment
        %div
            = f.text_area :content, class: 'text'
        %div
            = f.submit "Submit", class: 'btn-primary'

app/views/comments/index.html.haml
- @comments.each do |comment|
    = comment.content

app/views/comments/new.html.haml
= render 'form', comment: @comment

app/views/commons/_board.html.haml
= link_to board_path(board) do
    .card
        .card_top
            .card_title
                = board.title
            - if current_user == board.user
                .card_detail_actions
                    .dropdown
                        = image_tag 'actions.svg', class: 'dropbtn'
                        .dropdown-content.mini
                            = link_to 'Edit', edit_board_path(id: board.id)
                            = link_to 'Delete', board_path(id: board.id), data: { method: 'delete', confirm: '本当に削除してもよろしいですか？' }
        .card_content
            = board.description
        .card_user
            = image_tag board.user.avatar_image, class: 'user_image'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title TodoApp
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %link{:href => "https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css", :rel => "stylesheet"}/
  %body
    %div.top
      = link_to '/' do
        %h1.top_title Boards
      - if user_signed_in?
        .dropdown
          = image_tag current_user.avatar_image, class: 'user_image'
          .dropdown-content.mini
            = link_to 'プロフィール', profile_path
            = link_to 'ログアウト', destroy_user_session_path, method: :delete
      - else
        .dropdown
          = image_tag 'icon_image', class: 'user_image'
          .dropdown-content.mini
            = link_to 'ログイン', new_user_session_path
            = link_to '新規登録', new_user_registration_path
      - if flash.present?
        .flash
          - flash.each do |key, value|
            %div{:class => key}= value
    = yield

app/views/profiles/edit.html.haml
.container
    - @profile.errors.full_messages.each do |message|
        %ul
            %li=message
    = form_with(model: @profile, url: profile_path, method: 'put', local: true) do |f|
        %div
            = f.label :avatar, 'アバター'
        %div
            = f.file_field :avatar
        %div
            = f.label :nickname, "ニックネーム"
        %div
            = f.text_field :nickname, class: 'text'
        %div
            = f.label :introduction, '自己紹介'
        %div
            = f.text_area :introduction, class: 'text'
        %div
            = f.label :gender, '性別'
        %div
            = f.select :gender, Profile.genders.map{ |k,v| [ I18n.t("enum.genders.#{k}"), k ] }, {}, {class: 'text'}
        %div
            = f.label :subscribed, "通知を受け取る"
        %div
            = f.check_box :subscribed
        %div
            = f.submit "Submit", class: 'btn-primary'

app/views/profiles/show.html.haml
.container.profilePage
    %h2.section-top Profile
    .profilePage_user
        .profilePage_user_image
            = image_tag current_user.avatar_image
        .profilePage_user_basicInfo
            .profilePage_user_name
                .profilePage_user_displayName
                    #{current_user.display_name} (#{I18n.t("enum.genders.#{current_user.gender}")})
                .profilePage_user_actionButton
                    = link_to 'Edit', edit_profile_path
            .profilePage_user_introduction
                = current_user.introduction
    - current_user.boards.each do |board|
        = render 'commons/board', board: board

app/views/tasks/_card.html.haml
.container
    .card_top
        %h2.section-top= @task.title
        - if task.user == current_user
            .card_detail_actions
                .dropdown
                    = image_tag 'actions.svg', class: 'dropbtn'
                    .dropdown-content.mini
                        = link_to 'Edit', edit_task_path(task)
                        = link_to 'Delete', task_path(task), data: { method: 'delete', confirm: '本当に削除してもよろしいですか？' }
    .card
        - if task.eyecatch.attached?
            .card_image
                = image_tag @task.eyecatch
        .card_content
            内容：
            = task.content
        .card_limit
            期限：
            = task.limit.strftime('%Y年%m月%d日')
    .comments
        %h2.comments_top Comment
        - if task.comments.present?
            - task.comments.each do |comment|
                .comments_card
                    .comments_card_user
                        = image_tag comment.user.avatar_image, class: 'user_image'
                    .comments_card_content
                        = comment.content
        .card_add_board
            = link_to '+ Add new Comment', new_task_comment_path(task)

app/views/tasks/_form.html.haml
.container
    - if current_page?(new_board_task_path(task.board_id))
        %h2.section-top New Card
    - elsif current_page?(edit_board_task_path(task.id))
        %h2.section-top Edit Card
    - @task.errors.full_messages.each do |message|
        %ul
            %li= message
    = form_with(model: task, url: board_tasks_path(task.board), local: true) do |f|
        %div
            = f.label :eyecatch, "アイキャッチ"
        %div
            = f.file_field :eyecatch
        %div
            = f.label :title, "タイトル", class: 'form_eyecatch'
        %div
            = f.text_field :title, class: 'text'
        %div
            = f.label :content, "内容"
        %div
            = f.text_area :content, class: 'text'
        %div
            = f.label :limit, "期限"
        %div
            != sprintf(f.date_select(:limit, prefix:'task',with_css_classes:'XXXXX', prompt:"--",use_month_numbers:true, start_year:Time.now.year, date_separator:'%s'),'年','月')+'日'
        %div
        = f.submit "保存", class: 'btn-primary'

app/views/tasks/edit.html.haml
.container
    %h2.section-top New Card
    - @task.errors.full_messages.each do |message|
        %ul
            %li= message
    = form_with(model: @task, url: board_task_path(), method: 'put', local: true) do |f|
        %div
            = f.label :title, "タイトル"
        %div
            = f.text_field :title, class: 'text'
        %div
            = f.label :content, "内容"
        %div
            = f.text_area :content, class: 'text'
        %div
            = f.label :limit, "期限"
        %div
            != sprintf(f.date_select(:limit, prefix:'task',with_css_classes:'XXXXX', prompt:"--",use_month_numbers:true, start_year:Time.now.year, date_separator:'%s'),'年','月')+'日'
        %div
        = f.submit "保存", class: 'btn-primary'

app/views/tasks/new.html.haml
= render 'form', task: @task

app/views/tasks/show.html.haml
= render 'card', task: @task